// Copy the vendored protobuf definitions next to the compiled client so the
// runtime proto-loader can resolve them from the installed package, and emit
// src/generated-protos.ts embedding the same contents so a bundled build
// (e.g. the Codex MCP server) can extract them without shipping .proto files.
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const libProtoDir = join(root, 'lib', 'proto')
rmSync(libProtoDir, { recursive: true, force: true })
mkdirSync(libProtoDir, { recursive: true })
cpSync(join(root, 'src', 'proto'), libProtoDir, { recursive: true })
console.log('copied protos to lib/proto')

const protoDir = join(root, 'src', 'proto', 'nebula')
const files = ['graph.proto', 'common.proto', 'vector.proto']
const entries = files
  .map((file) => {
    const content = readFileSync(join(protoDir, file), 'utf8').replaceAll('`', '\\`').replaceAll('${', '\\${')
    return `  ${JSON.stringify(file)}: \`${content}\`,`
  })
  .join('\n')
const module = `/**
 * GENERATED by scripts/copy-proto.mjs — do not edit.
 *
 * Embedded copies of the vendored NebulaGraph 5.0 protocol definitions so a
 * fully bundled build (single-file MCP server) can materialize the .proto
 * files at runtime without shipping them on disk.
 */
export const EMBEDDED_PROTOS: Record<string, string> = {
${entries}
}
`
writeFileSync(join(root, 'src', 'generated-protos.ts'), module)
console.log('wrote src/generated-protos.ts')
